[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.18.0", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.96"
serde = "1.0.160"
tide = "0.16.0"
